spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
twitter:
  oauth:
    consumerKey: ${CONSUMER_KEY}
    consumerSecret: ${CONSUMER_SECRET}
    accessToken: ${ACCESS_TOKEN}
    accessTokenSecret: ${ACCESS_TOKEN_SECRET}
rabbit:
  queue:
    name: 'tweets'