version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - spring-cloud-services-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=tweets-cluster
    volumes:
      - 'esdata0:/usr/share/elasticsearch/data'
    networks:
      - spring-cloud-services-network
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - '$HOME/tweets-analyzer/postgres:/var/lib/postgresql/data'
    networks:
      - spring-cloud-services-network
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    volumes:
      - ~/.ssh:/root/.ssh:ro
    networks:
      - spring-cloud-services-network
  service-discovery:
    depends_on:
      - config-server
    container_name: service-discovery
    build:
      context: ./service-discovery
    networks:
      - spring-cloud-services-network
  twitter-integration:
    container_name: twitter-integration
    depends_on:
      - rabbitmq
      - config-server
      - service-discovery
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - EUREKA_SERVER=http://service-discovery:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    build:
      context: ./clients/twitter-integration
    volumes:
      - '$HOME/tweets-analyzer/twitter-integration/logs:/clients/twitter-integration/logs'
    networks:
      - spring-cloud-services-network
  es-integration:
    container_name: es-integration
    depends_on:
      - rabbitmq
      - elasticsearch
      - config-server
      - service-discovery
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    build:
      context: ./clients/es-integration
    volumes:
      - '$HOME/tweets-analyzer/es-integration/logs:/clients/es-integration/logs'
    networks:
      - spring-cloud-services-network
  user-service:
    container_name: user-service
    depends_on:
      - postgres
      - config-server
      - service-discovery
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
      - CONFIG_SERVER=http://config-server:8888
    build:
      context: ./clients/user-services/spring-data-jpa-user-service
    networks:
      - spring-cloud-services-network
  api-gateway:
    container_name: api-gateway
    depends_on:
      - service-discovery
    environment:
      - EUREKA_SERVER=http://service-discovery:8761/eureka
    build:
      context: ./api-gateway
    ports:
      - '8762:8762'
    networks:
      - spring-cloud-services-network

volumes:
  esdata0:
    driver: local
networks:
  spring-cloud-services-network:
    driver: bridge