version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: 'my-rabbit'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - spring-cloud-services-network

  twitter-integration:
    container_name: twitter-integration
    depends_on:
      - rabbitmq
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
      - RABBIT_HOST
      - RABBIT_USERNAME
      - RABBIT_PASSWORD
    build:
      context: ./clients/twitter-integration
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '$HOME/twitter-integration/logs:/clients/twitter-integration/logs twitter-integration'

    networks:
      - spring-cloud-services-network

networks:
  spring-cloud-services-network:
    driver: bridge