spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
rabbit:
  routing_key:
    name: 'tweets'
  queue:
    name: 'tweets'
  exchange:
    name: 'tweets_exchange'

